### ISSUE TITLE
Please adjust the error msg. when uploading tiffs

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#311]
#### Expected behaviour
I would either expect leihs to accept my uploaded tiff-file or to tell me that tiffs are not supported.  But this error msg. says something completely different.

#### Actual behaviour
When uploading a tiff in the edit model page, I get an error saying I do not have the priveleges to do what I am doing. 

#### Steps to reproduce
1. go to pool and edit a model
2. upload a tiff as image
3. you get an error

Please either accept tiffs or adjust the error msg. if possible: Tiff-extensions are not accepted. Please use XXX,  jpg, png. / Tiff-Bilder werden nicht akzeptiert. Bitte verwenden Sie XXX, jpg oder png. 

![when uploading a tiff](https://user-images.githubusercontent.com/3356016/30053521-716a1894-9229-11e7-9930-1dc8e6fe9867.jpeg)

**Comment by phiku** [comment]
Done

**Comment by nadjaweisskopf** [comment]
@phiku Still the same message appears when uploading a tiff on a model page.

**Comment by nadjaweisskopf** [comment]
I will create a new ticket for the points above.
